### ISSUE TITLE
Console Notebook support add/remove cell

### ISSUE THREAD

**Issue by allwefantasy** [allwefantasy/mlsql-api-console#9]
Related Project Address: https://github.com/allwefantasy/mlsql-web-console

![image](https://user-images.githubusercontent.com/797758/118613841-b6fd7f80-b7f1-11eb-82de-a5a4217783d0.png)

Current implementation lack of Add/Remove cell.

**Comment by githubnameting** [comment]
创建或者删除的cell 内容需要保存则需要接口的支持
1 创建 cell  url: /api_v1/script_file/${id}/create_cell
2 删除 cell url:  /api_v1/script_file/delete_cell/${notebookId}/${id}
3 获取notebook 详情即 cell list url: /api_v1/notebook/${id}/detail
接口ready 之后可进行联调

**Comment by githubnameting** [comment]
pr link 
https://github.com/allwefantasy/mlsql-web-console/pull/11
